### ISSUE TITLE
Problem when running pk over more than one simulated processor.

### ISSUE THREAD

**Issue by casqueais** [riscv-software-src/riscv-isa-sim#10]
When I try to run a simple Hello World test over spike pk simulating 2 processors, the system fails. I am invoking it like this:

$ spike -p2 pk hello

What I get from terminal is this:

![screenshot from 2014-11-18 15 58 22](https://cloud.githubusercontent.com/assets/5613271/5093085/d97c5050-6f3b-11e4-9ff7-9cbb1ece5e7d.png)

Am I doing something wrong here?

**Comment by noureddine-as** [comment]
Hello
Sir @aswaterman is pk still doesn't support multiple cores? (spike -p2 pk hello executes normally does this mean that it's now OK) ?

Is it possible for simple applications to run ontop of the proxy kernel and benefit from multi-core feature on real hardware (FPGA) ?  

Best regards,
Noureddine

**Comment by moy** [comment]
Indeed, pk doesn't support multiple cores: when running `spike -p 4 pk`, cores other than 0 execute [while(1) wfi();](https://github.com/riscv/riscv-pk/blob/e8e6b3aaee44d43b48164fbd377864c3a682dbd3/pk/pk.c#L222-L227) instead of the user's code.

**Comment by rahulvasta** [comment]
Can you please provide some pointers as to what all modules inside risc-pk needs to change to support multi-threading? 
Would the changes be minimal? Are there any plans to include multi-threading support soon?
As a starter for me, I have a minimial requirement in terms of getting multi-threading support from pk - My multi threaded application are bare metal and do not perform any syscalls. I just want the spike to boot pk with my multi threaded application.
Any pointers as to how can it be done?
