### ISSUE TITLE
Ecall still has H mode trap

### ISSUE THREAD

**Issue by poweihuang17** [riscv-software-src/riscv-isa-sim#115]
Hi, is the spike updated to the latest spec?
I found out that the ecall will still trap to H mode.
https://github.com/riscv/riscv-isa-sim/blob/5762bedab3a671ddfd279737d370533f31ed979e/riscv/insns/ecall.h

**Comment by aswaterman** [comment]
H-mode isn't implemented in Spike (see https://github.com/riscv/riscv-isa-sim/blob/5762bedab3a671ddfd279737d370533f31ed979e/riscv/processor.cc#L191), so this isn't a bug, but it is confusing.  I'll remove it.

**Comment by poweihuang17** [comment]
Got it. Thank you for the clarification. I will close this issue.
