### ISSUE TITLE
Calling convention doesn't match ISA spec

### ISSUE THREAD

**Issue by jugonz** [riscv-software-src/riscv-isa-sim#13]
The RISCV ISA spec (linked to from http://riscv.org/download.html) says that return values go into registers x16-x17 (v0-v1), yet these registers don't exist in `riscv/regnames.cc`. They used to, but commit 992205c27048709b85c2655bc5ce797dd2246f75 changed them to match the 'new' ABI.
What is this new ABI exactly?

**Comment by aswaterman** [comment]
https://blog.riscv.org/2015/01/announcing-the-risc-v-gcc-4-9-port-and-new-abi/

This will make it into the next version of the documentation.
