### ISSUE TITLE
potential RAW of FPR

### ISSUE THREAD

**Issue by hustcpp** [riscv-software-src/riscv-isa-sim#140]
Hi,

https://github.com/riscv/riscv-isa-sim/blob/a91d9f7d89abd6cda6fafb7b5e7cacf4b3590c29/riscv/insns/fmax_s.h#L5

This write could potentially affect following read, if FRD and FRS1/2 is the same register. Is this intentional?

https://github.com/riscv/riscv-isa-sim/blob/a91d9f7d89abd6cda6fafb7b5e7cacf4b3590c29/riscv/insns/fmax_s.h#L6

Note: FRS1/2 is reading directly from FPR.

Thanks,

**Comment by aswaterman** [comment]
This is a bug.  Thanks for finding it.  It's fixed here: https://github.com/riscv/riscv-isa-sim/commit/27ffc270f4e08862606e3532a87556e2f16fa87b
