### ISSUE TITLE
`li ra, 0` disassembles to `ret`

### ISSUE THREAD

**Issue by mwachs5** [riscv-software-src/riscv-isa-sim#152]
This is similar to #150 but I think this one may still be in the code as I am using riscv-tools @ eb34a2c2c4c5e317171feaad998cfe123ca272e6

Result from objdump:
```
20000000:	4081                	li	ra,0
```

Result from spike-dasm:
```
C0:       2933 [1] pc=[20000000] W[r 1=00000000][1] R[r 0=00000000] R[r 0=486e0e93] inst=[00004081] ret
```

**Comment by aswaterman** [comment]
thanks
