### ISSUE TITLE
Basic Block Vector generation for simpoint tool

### ISSUE THREAD

**Issue by sherry151** [riscv-software-src/riscv-isa-sim#16]
Hi folks,

I was wondering if someone is already working on adding basic block vector generation for simpoint flow so that I can collaborate. If not I will be happy to work on adding this feature into Spike. If you think there's something better out there than using simpoint, let me know!

**Comment by ccelio** [comment]
Nope, we don't know of anybody working on this, and you should definitely take it up!  Please keep us posted (I recommend using the official riscv.org mailing lists- you'll find more people to discuss this with). You may also want to investigate using QEMU for this instead of Spike.
