### ISSUE TITLE
Access to MSIP within CLINT causes system exceptions from Machine-mode

### ISSUE THREAD

**Issue by sherrbc1** [riscv-software-src/riscv-isa-sim#164]
A Machine-mode access to the MSIP register for hartid=0 within the CLINT periperhal will trigger a system exception with `mcause`=7 (Store/AMO access fault). 

`*((uint32_t *) CLINT_BASE + CLINT_H0_MSIP_OFFSET) = 1;`

And a Machine-mode access to the MSIP register for hartid=1 will trigger a system exception with `mcause`=6 (Store/AMO address misaligned) regardless of more than 1 CPU is being emulated (only 1 in dts shown below). It appears this exception triggers unless the access is 8-byte aligned, in which case the exception still triggers with `mcause`=7.

`*((uint32_t *) CLINT_BASE + CLINT_H1_MSIP_OFFSET) = 1;`

Where 

```
#define CLINT_BASE                (0x2000000)
#define CLINT_H0_MSIP_OFFSET      (0)
#define CLINT_H1_MSIP_OFFSET      (4)
```

Relevant clint definition: https://github.com/riscv/riscv-isa-sim/blob/master/riscv/clint.cc#L9-L10 and https://github.com/riscv/riscv-isa-sim/blob/master/riscv/clint.cc#L19.

```
$ spike --dump-dts
...
    #address-cells = <2>;
    #size-cells = <2>;
    compatible = "ucbbar,spike-bare-soc", "simple-bus";
    ranges;
    clint@2000000 {
      compatible = "riscv,clint0";
      interrupts-extended = <&CPU0_intc 3 &CPU0_intc 7 >;
      reg = <0x0 0x2000000 0x0 0xc0000>;
    };
  };
};

```

**Comment by sherrbc1** [comment]
The first problem turned out to be an access length issue in the CLINT implementation. The `msip` register is only 4 bytes wide, so accesses of any other length will fail with an access fault exception. 

https://github.com/riscv/riscv-isa-sim/blob/master/riscv/clint.cc#L42

The misalignment issue is unresolved.

**Comment by aswaterman** [comment]
I don't think it's a Spike bug.  You should examine the assembly code you're generating and make sure it's doing what you expect.  I see two problems with the C code:

- ```(uint32_t*)base + 4``` isn't what you want: you should either do ```(uint32_t*)(base + 4)``` or ```(uint32_t*)base + 1```.
- You should mark the pointer volatile.

**Comment by sherrbc1** [comment]
The pointer arithmetic is a mistake indeed, but the original problem was related to the CLINT implementation expecting MSIP accesses of width 4. I wrote my original code assuming 64 bit accesses while the example I provided coincidentally used 32. Aside from the arithmetic error you mention, the code works as expected (for 32 bit accesses).

**Comment by aswaterman** [comment]
Ah, I see.

The CLINT spec says only 32-bit accesses are supported.

**Comment by sherrbc1** [comment]
Only `msip` is defined as 32-bit. Both `mtime` and `mtimecmp` are 64-bit.
https://github.com/riscv/riscv-isa-sim/blob/master/riscv/devices.h#L69-L71

**Comment by aswaterman** [comment]
Sorry... I meant that MSIP bits only support 32-bit accesses.
