### ISSUE TITLE
autoconf fails on RHEL 6

### ISSUE THREAD

**Issue by sherry151** [riscv-software-src/riscv-isa-sim#17]
autoconf on RHEL6 fails with some m4_macro errors. The fix is to swap the position of two lines in configure.ac

Should be 

AC_INIT(proj_name,proj_version,proj_maintainer,proj_abbreviation)
AC_LANG_CPLUSPLUS

instead of 

AC_LANG_CPLUSPLUS
AC_INIT(proj_name,proj_version,proj_maintainer,proj_abbreviation)

**Comment by aswaterman** [comment]
Thanks, I'll add this patch.

**Comment by sherry151** [comment]
Fixed in master HEAD.
