### ISSUE TITLE
Mhartid in user mode?

### ISSUE THREAD

**Issue by rishikhan** [riscv-software-src/riscv-isa-sim#183]
Is there a reason that mhartid is not accessible from user mode? In my implementation, it's important to know which core you're on and it would be very helpful to be able to do so without trapping into a kernel. Is there any plans for uhartid or making mhartid readable in user-mode?

**Comment by aswaterman** [comment]
pthread_self() doesn’t require a kernel crossing, because the tp register (x4) is dedicated as the thread-local storage pointer.

**Comment by rishikhan** [comment]
I'm not using linux, but I see where you're going with this. If I have the data loaded from the kernel in thread local, it will solve the problem. THanks!
