### ISSUE TITLE
Running basic multi-core programs on Spike

### ISSUE THREAD

**Issue by noureddine-as** [riscv-software-src/riscv-isa-sim#188]
Hello,

I'm trying to build a multi-core platform, and I want to run some basic programs on it. Since I'm new to the RISC-V world and SoC design, I would like to know from where I can start?

- I was targetting a lite OS, something like FreeRTOS, but faced the problem reported in: https://github.com/illustris/FreeRTOS-RISCV/issues/10
Apparently here the FreeRTOS itself doesn't support multi-core functionality.
The main reason I wanted to try FreeRTOS was the fact that we want a very minimal OS that can support multi-cores. If there is any recommendations about that?

- So I decided to get back to something more basic. A simple program that would run ontop of the PK, but I've read here that pk doesn't support multi-core https://github.com/riscv/riscv-isa-sim/issues/10
However I don't get any errors when I run spike -p2 pk hello, so I guess it can support multi-cores now? Can it do that in real HW?

- What is the process of building multi-core applications? If an app works fine with the spike -p2 does this mean that it will perfectly run in HW (FPGA)?

I'm sorry for the very basic questions, but I could'nt find much information about that. Any help or recommendations would be appreciated, Thanks.
Best Regards.

**Comment by moy** [comment]
@noureddine-as : did you find a solution to your problem? Or did you just close the bug because there was no solution? In the first case, I'd be interested in your solution.

Thanks,
