### ISSUE TITLE
CSRR not printing out to commit log.

### ISSUE THREAD

**Issue by ccelio** [riscv-software-src/riscv-isa-sim#199]
What path does a `csrr stval` take (in the source code of spike)? It doesn't seem to hit the "commit_log_print_insn" even though it buffers up the write-data. 

If it is then followed up by a branch instruction, the commit log prints out the writeback data attached to the branch.

**Comment by aswaterman** [comment]
presumably a problem with instructions that call serialize().

CSR writes are OK?

**Comment by ccelio** [comment]
This has been reproduced using 3d016e2765f9ad5f34e471e345004c6e16438e3c but was not present in c746388b542eacd2586acfbc0a742b08a5c0bd6f.

It looks like no CSR instruction writes to the commit log now.

**Comment by ccelio** [comment]
Verified, thanks for this!
