### ISSUE TITLE
Debugging with gdb (remote bitbang): spike 100% cpu utilization

### ISSUE THREAD

**Issue by cgarlati** [riscv-software-src/riscv-isa-sim#203]
I am following the instructions in section "Debugging With Gdb" of the README.md. Everything works as expected although spike uses 100% cpu even if started with the -H option ("Start halted, allowing a debugger to connect").

Is this the expected behavior, a bug or am I doing something wrong? 

spike -H --rbb-port=9824 -m0x10000000:0x20000 rot13-64

Thanks! Cesare

**Comment by mwachs5** [comment]
The core keeps executing instructions even when "halted" in debug mode. It's running a little loop in the Debug ROM waiting for debugger to tell it what to do.

**Comment by cgarlati** [comment]
Thank you Megan for the prompt reply. I am closing this one as working as expected.

Note for future readers: below is the waiting loop in debug mode

core   0: 0x0000000000000814 (0xf1402473) csrr    s0, mhartid
core   0: 0x0000000000000818 (0x10802023) sw      s0, 256(zero)
core   0: 0x000000000000081c (0x40044403) lbu     s0, 1024(s0)
core   0: 0x0000000000000820 (0x00147413) andi    s0, s0, 1
core   0: 0x0000000000000824 (0x02041063) bnez    s0, pc + 32
core   0: 0x0000000000000828 (0xf1402473) csrr    s0, mhartid
core   0: 0x000000000000082c (0x40044403) lbu     s0, 1024(s0)
core   0: 0x0000000000000830 (0x00247413) andi    s0, s0, 2
core   0: 0x0000000000000834 (0xfc0418e3) bnez    s0, pc - 48
core   0: 0x0000000000000838 (0xfddff06f) j       pc - 0x24

**Comment by timsifive** [comment]
Note that this isn't nice behavior, and can probably be fixed by using `wfi` in that loop, and having the debug module kick the loop on every DMI access or something.
