### ISSUE TITLE
Dynamic instruction count in spike? (updated)

### ISSUE THREAD

**Issue by AhmedSamara** [riscv-software-src/riscv-isa-sim#211]
I saw issue #14 but this appears to be deprecated, when I run this I just get:

```
spike pk -s a.out 
../machine/mtrap.c:18: machine mode: unhandlable trap 4 @ 0x000000008000482e
```

**Comment by aswaterman** [comment]
That looks like an issue unrelated to the -s flag (but it's hard to say what it is).

**Comment by AhmedSamara** [comment]
Everything works fine without a -s flag.

**Comment by aswaterman** [comment]
I can't replicate it.  Can you upload your pk and a.out binaries somewhere?

**Comment by aswaterman** [comment]
and also indicate which commit of pk you are using?

**Comment by AhmedSamara** [comment]
https://ufile.io/pckjp

I am using [riscv-pk commit 3d921d3c76db3af7b9ae0b5df0f0790f26222246](https://github.com/riscv/riscv-pk/tree/3d921d3c76db3af7b9ae0b5df0f0790f26222246)

**Comment by aswaterman** [comment]
Looks like it's getting miscompiled.  https://github.com/riscv/riscv-pk/blob/3d921d3c76db3af7b9ae0b5df0f0790f26222246/machine/unprivileged_memory.h#L70 is getting compiled instead of the corresponding `#else` for some reason.

I don't have time to help debug why that might be, but it should at least give you a starting point.

**Comment by AhmedSamara** [comment]
Thank you for your help.

**Comment by AhmedSamara** [comment]
Question: why is logging dependant on compressed instructions being added?

**Comment by aswaterman** [comment]
Because the rdcycle instruction causes an illegal-instruction trap, and the illegal-instruction trap handler needs to know whether 32-bit-wide instructions are always naturally aligned.

**Comment by AhmedSamara** [comment]
So would this also fail under the 64 bit version of riscv-tools?

**Comment by aswaterman** [comment]
Possibly, but whether it actually fails depends on the alignment of the rdcycle instruction.
