### ISSUE TITLE
sstatus read/write issue

### ISSUE THREAD

**Issue by taoliug** [riscv-software-src/riscv-isa-sim#222]
I assume spike is currently implemented based on privileged spec 1.10. Here's the what mentioned in the 1.10 preface:
- MXR has been exposed to S-mode viasstatus. 
- The polarity of the PUM bit in sstatus has been inverted to shorten code sequences involving MXR. The bit has been renamed to SUM.

Here's how spike handles sstatus write, mxr can be written through sstatus
https://github.com/riscv/riscv-isa-sim/blob/master/riscv/processor.cc#L419
      reg_t mask = SSTATUS_SIE | SSTATUS_SPIE | SSTATUS_SPP | SSTATUS_FS
                 | SSTATUS_XS | SSTATUS_SUM | SSTATUS_MXR;

However, it cannot be read out
https://github.com/riscv/riscv-isa-sim/blob/master/riscv/processor.cc#L586
      reg_t mask = SSTATUS_SIE | SSTATUS_SPIE | SSTATUS_SPP | SSTATUS_FS
                 | SSTATUS_XS | SSTATUS_SUM | SSTATUS_UXL;

I don't understand why the read/write mask is different, there are two issues:
1. sstatus.uxl cannot be written
2. sstatus.mxr cannot be read

Can you take a look?

**Comment by aswaterman** [comment]
It's intentional that UXL isn't writable: Spike doesn't currently support that option.

MXR not being readable is clearly a bug; I've fixed it with 1ff2a70ec87c0a418ca38cdff9b14fc29e4b1ecb -- thanks for the bug report.
