### ISSUE TITLE
spike-dasm issue 

### ISSUE THREAD

**Issue by Chakri-myneni** [riscv-software-src/riscv-isa-sim#228]
Hello everyone,
When I run **cat spike.log | spike-dasm**  the output is exactly same as spike.log. Which means my log file is directly getting printed on screen without going to spike-dasm. 
I even tried **cat spike.log | $RISCV/bin/spike-dasm**, but the result is same as spike.log.

Here is the picture of my log
![spike-log](https://user-images.githubusercontent.com/42030248/43893600-2308639e-9bed-11e8-9dde-35e1c086eff3.png)

My question
1. how do I get disassembled output(using spike-dasm) of my log file that is generated through **spike -l** ?

Thank you,
Chakri

**Comment by neelgala** [comment]
spike-dasm will disassemble the contents within the DASM(hexvalue_here) string. Example:

echo "DASM(0x00000297)"| spike-dasm 

will print 

auipc   t0, 0x0

Since the spike.log doesn't have the DASM directive spike-dasm will not print anything extra.

**Comment by Chakri-myneni** [comment]
Thank you @neelgala 

An output like following pic
![logpic](https://user-images.githubusercontent.com/42030248/43895351-a3c4fd26-9bf2-11e8-810f-48123ef307b6.JPG)

Is it possible using Rocket only or can be done using spike also?
