### ISSUE TITLE
Riscv function simulation model ???

### ISSUE THREAD

**Issue by IC-Dream** [riscv-software-src/riscv-isa-sim#236]
Hi,

Is there a riscv function simulation model ? we could get the golden information using the model, like pc,instruction executed, updated register.

Thanks
Dream

**Comment by aswaterman** [comment]
That's what this repo is.  You can have Spike dump some trace information with the `-l` flag.

**Comment by IC-Dream** [comment]
Thanks a lot, I have tried, but i didn't see any execution result in the trace information. for example, the following "addi", the updated value was not printed. 
![l2 qyvg_is bafukl4 2t](https://user-images.githubusercontent.com/39543344/45197344-42799100-b293-11e8-95d6-00a79811d6e8.png)

**Comment by aswaterman** [comment]
You can also check out the commit-log feature (run the configure script with --enable-commit-log).  It might serve your purpose.
