### ISSUE TITLE
Floating number conversion issue

### ISSUE THREAD

**Issue by haroldtsai** [riscv-software-src/riscv-isa-sim#244]
Dear all,

I have a question about float -> unsigned num.
Took fcvt_wu_s instruction as example; I give these inputs:

1. 0xafc7529e as  input floating(a small negative number)
2. rounding mode is 0 

The output unsigned number is 0 which is the expected answer. 
But I am curious about the exception flags. 
Spike shows the "**inexact**" flag. But according to spec 

> If the rounded result is not representable in the destination format, it is clipped to the nearest value and the invalid flag is set. (chapter 8.7 table 8.4)

why the **inexact** flag is arisen instead of **invalid** flag?

**Comment by aswaterman** [comment]
After rounding, the result is 0, which *is* representable in the destination format.  Therefore, the result is not invalid.
