### ISSUE TITLE
for a fmadd.s: (+0.0) * (+0.0) +（-0.0）, spike returns (+0.0)  ????

### ISSUE THREAD

**Issue by IC-Dream** [riscv-software-src/riscv-isa-sim#258]
Hi, 

For a fmadd.s like the below from spike commit log:
![log](https://user-images.githubusercontent.com/39543344/48761359-64f04780-ece3-11e8-8f18-6400d6533c67.PNG)

Why not return 0x8000_0000 ???  or both the two results are permitted ????

Thanks
Dream

**Comment by aswaterman** [comment]
+0 + -0 is defined to be +0, not -0.  Spike is correct and the other option would be incorrect.
