### ISSUE TITLE
for a fle.s, spike assume that (+0) <= (-0) ???

### ISSUE THREAD

**Issue by IC-Dream** [riscv-software-src/riscv-isa-sim#259]
Hi,

I wrote a directed case to test fle.s, and the following is the commit log from spike:
![fles](https://user-images.githubusercontent.com/39543344/48823934-a2191000-ed9d-11e8-878f-1389a4dd13b7.PNG)

Here is dissasembly:
![fle dis](https://user-images.githubusercontent.com/39543344/48823959-b3fab300-ed9d-11e8-8da2-dbd38651695d.PNG)

From the two snopshot above, we could see that the spike assume that (+0) <= (-0), so is this legal ???

Thanks
Dream

**Comment by aswaterman** [comment]
That’s correct behavior per IEEE 754. +0 and -0 are defined to be equal.
