### ISSUE TITLE
when s mode is not support, should we permit it execute sfence.vma in m mode?

### ISSUE THREAD

**Issue by XIONGLIWEN** [riscv-software-src/riscv-isa-sim#281]
Now the s mode is not support, the mstatus.TVM is tie to zero. then sfence.vma is permit in s mode . when we execute it in M Mode, the spike will permit it . because the require_privilege function will return true ,when the privilege mode is more than S mode . so execute sfence.vma will treat as be fence.i or fence in M mode , Do it right ?

**Comment by aswaterman** [comment]
Spike is not currently designed to support implementations without S-mode, so you should not follow its advice on this matter.

If your implementation does not have S-mode, you should not implement the SFENCE.VMA instruction (or the SRET instruction).
