### ISSUE TITLE
How does spike set breakpoint debugging?What does spike -d pk files output?

### ISSUE THREAD

**Issue by mouhuajun** [riscv-software-src/riscv-isa-sim#282]
How does spike set breakpoint debugging?What does spike -d pk files output?

**Comment by aswaterman** [comment]
`spike -d` is a debug mode, so you can single-step through the instruction stream and examine the architectural state of the machine.  It also provides the ability to run until the PC hits some value, which is effectively a breakpoint.

If you type `help` at the console you see when you run `spike -d program`, you can see some of the very basic commands it allows.

**Comment by omerguzelelectronicguy** [comment]
@aswaterman This debug mode is different from what riscv debug specification is right? I mean spike supports debug mode specification of riscv architecture(I guess). but when we run spike with -d flag, it makes it easier to follow the program(not to implement the debug mode of riscv).

**Comment by aswaterman** [comment]
That's right.  Spike implements the RISC-V debug architecture, but that has nothing to do with the `-d` command-line argument.

**Comment by omerguzelelectronicguy** [comment]
I think this can be closed.
