### ISSUE TITLE
spike can't run riscv64-unknown-linux-gnu compiled executable file

### ISSUE THREAD

**Issue by ericwu13** [riscv-software-src/riscv-isa-sim#300]
I want to use Spike to simulate the glibc compiled program since newlibs version can't add -pg option to do gprof. I want to use riscv64-unknown-linux-gnu-gcc to enable -pg option. But I stuck just in the beginning.

I compiled my program using below command.
```bash
$ riscv64-unknown-linux-gnu-gcc hello.c 
```
And I use riscv-tools to build spike and pk, setting host of build-spike-pk.sh to riscv-unknown-linux-gnu
and successfully build them

Later I run the below command

```bash
$ spike pk a.out
```
It turn out segfault (my pk is pointing to the riscv-unknown-linux-gnu/bin/pk). The below is error message.
![image](https://user-images.githubusercontent.com/37173038/57581777-f4d2b980-74ee-11e9-9eaa-c61f0b95b3ca.png)

My program
```c++
#include <stdio.h>
int main() {
     printf("Hello\n");
     return 0;
}
```
I wonder if spike can simulate the glibc, and how to do it? Or should I use qemu to do? If so, can anyone provide the link of riscv qemu installation (the github is archived though...). Thanks!

**Comment by aswaterman** [comment]
Spike can only run statically linked programs, whereas the Linux compiler dynamically links by default. If you add the -static flag it will work.

**Comment by ericwu13** [comment]
Hi, Thanks for your reply, now I got three problems. Could you help me?
1. I've added static flag to the compiler, however, it printed the below error

![image](https://user-images.githubusercontent.com/37173038/57589764-1d8f9900-7559-11e9-9267-36f435bce5ed.png)

I used ct-ng to build the riscv64-unknown-linux-gnu toolchains, with kernel version 4.19 and I'm using ubuntu 16.04, how to solve it? I encountered the same problem running qemu-riscv64, too.

Another question is, I need to do this to enable pk
```
$ spike $(which pk) <BIN>
```
2. instead of the below, which will result in the next error, I've set isa-sim target and pk host to riscv64-unknown-linux-gnu to build spike and pk, but still can't work. Though, PATH is properly set ($RISCV/bin and $RISCV/riscv64-unknown-linux-gny/bin)
```
$ spike pk <BIN>
```
![image](https://user-images.githubusercontent.com/37173038/57589807-7eb76c80-7559-11e9-950c-8ef77d406f94.png)

3. I wonder if spike is able to run -pg compiled program? My ultimate goal is to do gprof. Don't know if it is feasible. Thanks

**Comment by aswaterman** [comment]
Ah, my Linux compiler must be older than yours. In that case, I recommend
using an elf compiler instead of a linux one.

**Comment by ericwu13** [comment]
but the elf one can't add -pg flag to do profiling. I think I'll try build an older linux compiler.

**Comment by ericwu13** [comment]
I've solved the problem by installing riscv compiler using riscv-gnu-toolchains, instead of ct-ng. I think it is because my gcc and c version is 5.4 to build spike and qemu while i'm using 8.3 in ct-ng to build compiler... But I can't change it to lower version though. Anyway, using riscv-gnu-toolchains to build from source works for me.
