### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by Fan-f1bu** [riscv-software-src/riscv-isa-sim#307]
make fails with the following error:

../riscv/decode.h:1366:24: error: variable-sized object ‘index’ may not be initialized
 reg_t index[vlmax] = {0}; \

**Comment by aswaterman** [comment]
Thank you for the bug report.  We didn't notice this because it works fine on recent versions of GCC, but it's nonstandard code that Clang rejects.  We will fix it.

**Comment by Fan-f1bu** [comment]
Thank you! I wish you can complete it successfully.
