### ISSUE TITLE
why  does ”CLINT“ cost so large(0xc00000) address space 

### ISSUE THREAD

**Issue by dskwe** [riscv-software-src/riscv-isa-sim#310]
@aswaterman I found spike defined a "clint" device which start from 0x02000000 to 0x020c0000. 

I got "CLINT is a name we have used at SiFive to cover the local interrupts described in the privileged architecture standard v1.10, including the software interrupts, the timer interrupts, the external interrupt (which is usually in turn connected to a PLIC), and any additional local interrupts made visible in the mip/mie CSRs bits 16 and above. These same interrupt sources can now be also accessed via CLIC mode, which is a draft proposal with the [Foundation."](https://forums.sifive.com/t/does-the-risc-v-foundation-have-a-description-and-definition-of-clint/1406)

I'm puzzled for why "CLINT" cost so so large(0xc00000) address space. What is it designed to do, just for keeping consistency with siFive hardware implementation? Hope your reply.

**Comment by aswaterman** [comment]
Yes, wanted to have a unified address map. It’s large because it supports a
large number of harts without changing the address map.
