### ISSUE TITLE
Vector instruction is decoded while running spike with --isa=rv32imc

### ISSUE THREAD

**Issue by taoliug** [riscv-software-src/riscv-isa-sim#313]
I am doing a random illegal instruction testing. Some none RV32IMC instructions are simulated, and I expect spike to raise an illegal instruction exception for this. However, seems like spike executed this instruction as vector instruction and no error is reported. Is this intended behavior?

core   0: 0xffffffff8000f6d6 (0xe8ec20d7) vwmulsu.vv v1, v14, v24, v0.t

**Comment by taoliug** [comment]
Is there a way to disable vector extensions while building spike?

**Comment by aswaterman** [comment]
This is a bug in the experimental vector support.  The instructions should not be available with `--isa=rv32imc`.  I will fix it.
