### ISSUE TITLE
spike can't recognize MTVT CSR

### ISSUE THREAD

**Issue by weiqi7777** [riscv-software-src/riscv-isa-sim#318]
hi:
   I see CSR_MTVT is defined in encoding.h.  but it doesn't implement in processor.cc. 
   that cause that accessing mtvt CSR will generate exception. 
   in riscv-tests, some case will access MTVT CSR.
can you help to look it?
thanks

**Comment by aswaterman** [comment]
Spike doesn't support the CLIC.

**Comment by weiqi7777** [comment]
thanks for your replay.
i close these issue.
