### ISSUE TITLE
Minor (but important!) issue in Readme.md

### ISSUE THREAD

**Issue by dylanmc** [riscv-software-src/riscv-isa-sim#328]
I was looking for how to single-step spike. For some reason, the markdown viewer shows this:

> You can advance by one instruction by pressing . You can also execute until a desired equality is reached:

I thought it was trying to tell me to use the . key, but that didn't work. Looking at the raw Readme.md, I see that it should have been `<enter>`, but the angle brackets trigger markdown's HTML mode, I think, so enclosing them in back-ticks should fix it. I would be happy to fork, fix, and create a pull request, but wasn't sure that was warranted for such a trivial fix.

**Comment by aswaterman** [comment]
That sure is confusing!  I've fixed it by writing out "the enter key" instead.
