### ISSUE TITLE
Error when following "Debugging with Gdb" section in Readme.md

### ISSUE THREAD

**Issue by luoxinjie1146** [riscv-software-src/riscv-isa-sim#329]
When I run `spike --rbb-port=9824 -m0x10000000:0x20000 rot13-64`, the following error occured:
```
Listening for remote bitbang connection on port 9824.
warning: tohost and fromhost symbols not in ELF; can't communicate with target
```
Is this correct or I should do something to fix it?
I tried strip like `riscv64-unknown-elf-strip -s -Kfromhost -Ktohost rot13-64`, but it doesn't work.

When I run `openocd -f spike.cfg`, the following error occured:
```
Open On-Chip Debugger 0.9.0 (2018-01-24-01:05)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Warn : Adapter driver 'remote_bitbang' did not declare which transports it allows; assuming legacy JTAG-only
Info : only one transport option; autoselect 'jtag'
embedded:startup.tcl:21: Error: Unknown target type riscv, try one of arm7tdmi, arm9tdmi, arm920t, arm720t, arm966e, arm946e, arm926ejs, fa526, feroceon, dragonite, xscale, cortex_m, cortex_a, cortex_r4, arm11, mips_m4k, avr, dsp563xx, dsp5680xx, testee, avr32_ap7k, hla_target, nds32_v2, nds32_v3, nds32_v3m, or1k,  or quark_x10xx
in procedure 'script' 
at file "embedded:startup.tcl", line 60
in procedure 'target' called at file "spike.cfg", line 9
in procedure 'ocd_bouncer' 
at file "embedded:startup.tcl", line 21
```
How can I fix it.

**Comment by timsifive** [comment]
The output of spike looks normal.

The output of OpenOCD indicates you're running an OpenOCD that doesn't have RISC-V support. You can get one that does at https://github.com/riscv/riscv-openocd.

**Comment by luoxinjie1146** [comment]
Thanks for your answer @timsifive . I tried to build OpenOCD from [https://github.com/riscv/riscv-tools](url), should I add some options when running `./configure`?

**Comment by timsifive** [comment]
You need `--enable-remote-bitbang` to be able to talk to spike.

**Comment by luoxinjie1146** [comment]
I used the following commands,
```
--prefix=$RISCV --enable-remote-bitbang --enable-jtag_vpi --disable-werror
make
make install
```
Did I miss something?

**Comment by timsifive** [comment]
That looks good to me.

**Comment by luoxinjie1146** [comment]
Thanks a lot. I didn't running the right openocd binary! I will close this issue now

**Comment by WilliamWangPeng** [comment]
@timsifive  
hi Tim at SiFive
    Nice to meet you, dear Tm at SiFive, This is William, I have some questions about debugging with GDB following the website
https://github.com/riscv/riscv-isa-sim
I followed the steps on debugging with GDB, inputting the parameters
https://github.com/riscv/riscv-isa-sim/issues/329


--prefix=$RISCV --enable-remote-bitbang --enable-jtag_vpi --disable-werrormake 
make install

  but getting some results below:

pwang@york:~/test$ openocd -f spike.cfg
Open On-Chip Debugger 0.10.0+dev-00198-g35eed36ff (2019-09-29-23:43)
Licensed under GNU GPL v2
For bug reports, read
    http://openocd.org/doc/doxygen/bugs.html
Warn : Adapter driver 'remote_bitbang' did not declare which transports it allows; assuming legacy JTAG-only
Info : only one transport option; autoselect 'jtag'
Info : Initializing remote_bitbang driver
Info : Connecting to localhost:9824
Error: Failed to connect: Connection refused

do you know what is wrong and how can I fix it?
 thank you so much
Yours William

**Comment by timsifive** [comment]
It looks like spike isn't running, or you didn't use --rbb-port=9824 when
you started it.

Tim
