### ISSUE TITLE
vsetvli with SEW length 8 sets the vl register to 15 instead of 16

### ISSUE THREAD

**Issue by wyattp** [riscv-software-src/riscv-isa-sim#331]
Setting the vector length with vsetvli and a element width of 8 results in the new vl register having a value of 15 rather than 16

ex: vsetvli     a1, t1, e32
sets a1 to 15

**Comment by aswaterman** [comment]
I take it that `t1` is >= 16 in this example?

**Comment by wyattp** [comment]
i made a mistake, t1 wasnt defined in the example I was running. setting t1 to 16 or higher yields the correct result. Looks like the undefined t1 register defaults to 15

**Comment by aswaterman** [comment]
Cool!
