### ISSUE TITLE
instruction count in log

### ISSUE THREAD

**Issue by kalairajah** [riscv-software-src/riscv-isa-sim#333]
Hi,
 Is there a way to print the instruction number before each instruction when spike executes it, Currently, I don't see any option that can be passed to spike to print this information. 

Here is an example of what I currently see in the logs for an instruction executed ..

core 0:  0x00000000800001664 (0xc9d80d93) addi s11, a6, -867
3 0x00000000800001664 (0xc9d80d93) x27 0xffffffffe8866c9c

I donot use pk and run spike as follows:
spike -l elf 2>& spike.out

Thanks,
Kalai

**Comment by aswaterman** [comment]
You can post-process the log using something like `nl spike.out`

**Comment by kalairajah** [comment]
Thanks . Is there any plan to add it as part of the regular run instead of post processing the output.

**Comment by aswaterman** [comment]
No, it's not practical to add command-line options to make the log look exactly right for each use case, so we'd prefer to rely on post-processing to clean things up.
