### ISSUE TITLE
How to assemble the "V" extension?

### ISSUE THREAD

**Issue by luoxinjie1146** [riscv-software-src/riscv-isa-sim#334]
I noticed that the spike has supported "V" extension. But I'm getting confused how to assemble the "V" extension to excutable ELF files. Is it possible to run a program with "V" extension now?

**Comment by chihminchao** [comment]
Yes. The master branch  has supported the vector spec 0.7.1 and you could the [rvv toolchain](https://github.com/riscv/riscv-gnu-toolchain/commits/rvv-0.7.1) to evaluate spec

**Comment by luoxinjie1146** [comment]
Thanks @chihminchao .
