### ISSUE TITLE
Disabling unimplemented processor modes User and Supervisor

### ISSUE THREAD

**Issue by sdexter-numa** [riscv-software-src/riscv-isa-sim#336]
Is it possible in Spike to expect User and Supervisor modes to be disabled? This is an issue in my use case, because the Spike logger always expects certain bits of the mstatus CSR to be set, but they will never be set if the riscv processor dut is only in Machine Mode.

**Comment by aswaterman** [comment]
Not currently. You’ll need to hack the code to accomplish this.

**Comment by sdexter-numa** [comment]
I was able to find a workaround. I'm using google's riscv-dv instruction generator, and it's possible within that to disable some bits in mstatus from ever being set, which means Spike won't take any issue with it.
