### ISSUE TITLE
problem in installation

### ISSUE THREAD

**Issue by amitgargmentor** [riscv-software-src/riscv-isa-sim#343]
Hi, 

README file mention the below steps to install the SPIKE ISA SIM. 
 apt-get install device-tree-compiler

since i have RED HAT OS, i use the below command:
sudo yum install device-tree-compiler 

but it gives me below error:

**Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
No package device-tree-compiler available.
Error: Nothing to do**

can someone please help ? 

Thanks

**Comment by chihminchao** [comment]
I think the package in RedHat distribution may differ from Ubuntu.
Have you tried `yum install dtc`

**Comment by amitgargmentor** [comment]
the issue is already resolved. I need to install DTC.
