### ISSUE TITLE
add security tags into the Spike pipeline

### ISSUE THREAD

**Issue by WilliamWangPeng** [riscv-software-src/riscv-isa-sim#365]
hi dear guys
I want to add security tags which is 64 bits double word associated with 4 bits tags into the Spike pipeline, do you have some ideas?

**Comment by heshamelmatary** [comment]
You may wanna look at [CHERI-Spike](https://github.com/CTSRD-CHERI/riscv-isa-sim) which has support for tags.  Have a look at where/how _[tag_t](https://github.com/CTSRD-CHERI/riscv-isa-sim/blob/da2ef165be48cde2e9305654c355f40bd0b10c1c/riscv/tags.h#L40)_ is defined and used.
