### ISSUE TITLE
Duplicate vectorUnit_t

### ISSUE THREAD

**Issue by scottj97** [riscv-software-src/riscv-isa-sim#385]
@chihminchao commit 4a6b6946bddd6569cc1086acee528b981fc08b93 moved vectorUnit_t into processor_t but did not delete the old, apparently-no-longer-used vectorUnit_t. Now there are two classes named vectorUnit_t in processor.h.

**Comment by chihminchao** [comment]
It is my fault and I have send an PR https://github.com/riscv/riscv-isa-sim/pull/387.

**Comment by aswaterman** [comment]
#387 has been merged.
