### ISSUE TITLE
Upper 10 bits of PMPADDR* should be wired to 0 in RV64

### ISSUE THREAD

**Issue by scottj97** [riscv-software-src/riscv-isa-sim#386]
According to the priv spec (Version 20190608-Priv-MSU-Ratified) figure 3.27 ("PMP address register format, RV64"), bits [63:54] are hard-wired to 0.

In my testing, when I do `csrw` followed by `csrr` to `pmpaddr0`, I see that Spike stores and reads back all 64 bits.

**Comment by aswaterman** [comment]
Thanks for the bug report. I’ll fix this shortly.

**Comment by scottj97** [comment]
This is not quite there...the initial value of `pmpaddr0` is still illegal.

**Comment by aswaterman** [comment]
Fixed in cb254bfab5fbb6d69e5dd336798861e7c1183e52
