### ISSUE TITLE
unable to simulate vector extension

### ISSUE THREAD

**Issue by bbougenot** [riscv-software-src/riscv-isa-sim#438]
I've attempted to simulate vector instructions using "spike --isa=RV64IMAFDCV" but it seems any isa argument with the vector extension included leads to: "error: bad --isa option RV64IMAFDCV".

**Comment by bbougenot** [comment]
I was using the default spike version from riscv-tools instead of the updated version. Sorry!

**Comment by bryce7777** [comment]
> 
Hi bbougenot, wha does the updated version mean? I have the same issue -- "... bad --isa option ..." when I try to simulate vector instructions. Thank you !
