### ISSUE TITLE
unrecognized option --gdb-port

### ISSUE THREAD

**Issue by quantrpeter** [riscv-software-src/riscv-isa-sim#445]
hi
   i am using mac, i have spike by building riscv-tools. but it doesn't comes with --gdb-port, plesae help?

```
/Users/peter/workspace/risc-v/hello>spike --gdb-port=1234 pk hello
spike: unrecognized option --gdb-port=1234
Try 'spike --help' for more information.
```

thanks
Peter

**Comment by timsifive** [comment]
--gdb-port only existed briefly. --rbb-port is what you want, as described
in the README.md file.
