### ISSUE TITLE
Add support for other RISC-V processors

### ISSUE THREAD

**Issue by YashxD** [riscv-software-src/riscv-isa-sim#468]
I am looking to add a new processor to spike (other than SiFive) so I can simulate my own product.
Not sure how to go about it. I went through the source code but it's too complicated for me to understand (I'm just a college student). Not sure where to ask for help regarding this so trying out here.

**Comment by chihminchao** [comment]
What new features do you need ? To add new instructions or something else ?

**Comment by YashxD** [comment]
I had the issue wrong. This isn't what I needed. Thanks @chihminchao for the prompt reply!
