### ISSUE TITLE
Does Hwacha support GDB for debugging？

### ISSUE THREAD

**Issue by kangrl666** [riscv-software-src/riscv-isa-sim#472]
1.Does Hwacha support GDB for debugging？

2.Run command“spike -H --rbb-port=9824 --extension=hwacha vec-vvadd.riscv”，this program doesn‘t start halted，directly output results，not allowing a debugger to connect。

But run command“spike -H --rbb-port=9824 vvadd.riscv”，this program start halted。spike connects openocd， openocd connects GDB，both are ok，debugging is ok。

why？the command“spike -H” is right for RISC-V，but not right for Hwacha? how to solve the problem for debugging Hwacha instructions？

**Comment by colinschmidt** [comment]
I've responded on the hwacha issue and think we should keep the discussion there. Closing this now.
