### ISSUE TITLE
trying build spike

### ISSUE THREAD

**Issue by suhasskrishanmurthy** [riscv-software-src/riscv-isa-sim#481]
Hi, I was trying to build spike and got this error,
it is saying  CSR_VSTART variables are not declared in scope.

make: Circular libsoftfloat.so <- libsoftfloat.so dependency dropped.
g++ -MMD -MP  -Wall -Wno-unused -g -O2 -std=c++11 -DPREFIX=\"/usr/local\" -I. -I.. -I../fesvr -I../riscv -I../dummy_rocc -I../softfloat -I../spike_main  -c ../riscv/processor.cc
../riscv/processor.cc: In member function ‘void processor_t::set_csr(int, reg_t)’:
../riscv/processor.cc:694:10: error: ‘CSR_VSTART’ was not declared in this scope
     case CSR_VSTART:
          ^~~~~~~~~~
../riscv/processor.cc:694:10: note: suggested alternative: ‘ERESTART’
     case CSR_VSTART:
          ^~~~~~~~~~
          ERESTART
../riscv/processor.cc:697:10: error: ‘CSR_VXSAT’ was not declared in this scope
     case CSR_VXSAT:
          ^~~~~~~~~
../riscv/processor.cc:697:10: note: suggested alternative: ‘CSR_SATP’
     case CSR_VXSAT:
          ^~~~~~~~~
          CSR_SATP
../riscv/processor.cc:700:10: error: ‘CSR_VXRM’ was not declared in this scope
     case CSR_VXRM:
          ^~~~~~~~
../riscv/processor.cc:700:10: note: suggested alternative: ‘CSR_FRM’
     case CSR_VXRM:
          ^~~~~~~~
          CSR_FRM
../riscv/processor.cc: In member function ‘reg_t processor_t::get_csr(int)’:
../riscv/processor.cc:872:10: error: ‘CSR_VSTART’ was not declared in this scope
     case CSR_VSTART:
          ^~~~~~~~~~
../riscv/processor.cc:872:10: note: suggested alternative: ‘ERESTART’
     case CSR_VSTART:
          ^~~~~~~~~~
          ERESTART
../riscv/processor.cc:877:10: error: ‘CSR_VXSAT’ was not declared in this scope
     case CSR_VXSAT:
          ^~~~~~~~~
../riscv/processor.cc:877:10: note: suggested alternative: ‘CSR_SATP’
     case CSR_VXSAT:
          ^~~~~~~~~
          CSR_SATP
../riscv/processor.cc:882:10: error: ‘CSR_VXRM’ was not declared in this scope
     case CSR_VXRM:
          ^~~~~~~~
../riscv/processor.cc:882:10: note: suggested alternative: ‘CSR_FRM’
     case CSR_VXRM:
          ^~~~~~~~
          CSR_FRM
../riscv/processor.cc:887:10: error: ‘CSR_VL’ was not declared in this scope
     case CSR_VL:
          ^~~~~~
../riscv/processor.cc:887:10: note: suggested alternative: ‘CSR_MTVAL’
     case CSR_VL:
          ^~~~~~
          CSR_MTVAL
../riscv/processor.cc:892:10: error: ‘CSR_VTYPE’ was not declared in this scope
     case CSR_VTYPE:
          ^~~~~~~~~
../riscv/processor.cc:892:10: note: suggested alternative: ‘CSR_TIME’
     case CSR_VTYPE:
          ^~~~~~~~~
          CSR_TIME
In file included from ../riscv/processor.cc:3:0:
./insn_list.h: In member function ‘void processor_t::register_base_instructions()’:
./insn_list.h:216:13: error: ‘vfadd_vf_match’ was not declared in this scope
 DEFINE_INSN(vfadd_vf)
             ^
../riscv/processor.h:480:37: note: in definition of macro ‘REGISTER_INSN’
   proc->register_insn((insn_desc_t){match, mask, rv32_##name, rv64_##name});
                                     ^~~~~
./insn_list.h:216:1: note: in expansion of macro ‘DEFINE_INSN’
 DEFINE_INSN(vfadd_vf)
 ^~~~~~~~~~~
./insn_list.h:216:13: note: suggested alternative: ‘fadd_q_match’
 DEFINE_INSN(vfadd_vf)
             ^
../riscv/processor.h:480:37: note: in definition of macro ‘REGISTER_INSN’
   proc->register_insn((insn_desc_t){match, mask, rv32_##name, rv64_##name});
                                     ^~~~~
./insn_list.h:216:1: note: in expansion of macro ‘DEFINE_INSN’
 DEFINE_INSN(vfadd_vf)
 ^~~~~~~~~~~
./insn_list.h:216:13: error: ‘vfadd_vf_mask’ was not declared in this scope
 DEFINE_INSN(vfadd_vf)

Please help, why is it showing like this.

**Comment by chihminchao** [comment]
Could you provide the spike version, configure argument and building environment (host OS and compiler version) ?
