### ISSUE TITLE
CXXABI_1.3.8/GLIBCXX_3.4.20 not found

### ISSUE THREAD

**Issue by DisturbedShadow** [riscv-software-src/riscv-isa-sim#484]
Hello everyone, I am having a problem while trying to execute and simulate a file with spike. I am getting this error: 

spike: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by spike)
spike: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by spike)

I have searched in some posts to invoke the newest libraries or change the LD_LIBRARY_PATH env var, to run with spike but it does not work.
My server gcc gnu version is 2014 but the riscv-toolchain is the latest one.

Thank you in advance

**Comment by aswaterman** [comment]
Doesn't seem like a Spike issue.  Sounds like the kind of thing that happens when you compiled it in a different environment than you executed it in.

**Comment by DisturbedShadow** [comment]
I've put the bin folder with all the necessary files into my PATH so I can execute them in a different folder, I guess this does not count?

**Comment by aswaterman** [comment]
Seems like your runtime environment has an older libstdc++ version than your compile-time environment.  Sorry, I can't help more than that.

**Comment by kito-cheng** [comment]
The easiest solution is recompile spike again on your environment, or recompile it with "-static-libstdc++".

**Comment by DisturbedShadow** [comment]
How can I do that, I'm really new to everything.

**Comment by DisturbedShadow** [comment]
What happens is that when I install spike on a different folder and not in riscv tools path then it works but then I can not use pk.

**Comment by DisturbedShadow** [comment]
Solution:

If you want to execute spike everywhere like I wanted add spike to your PATH var then create an export var for the pk binary file (example: export pk=/path/to/your_pk_file) and if you want to use spike with rv32i isa, use it like this : spike --isa=rv32i $pk <your_program_for_sim.elf>

Thank you everyone for commenting
