### ISSUE TITLE
What is the option of vector isa when running spike ? --isa=rv32iv

### ISSUE THREAD

**Issue by WilliamWangPeng** [riscv-software-src/riscv-isa-sim#492]
Hi everyone  
```  
spike --isa=rv32im ./rv64/riscv-tools/riscv-gnu-toolchain/riscv32-unknown-elf/bin/pk ./test/t1    
```  
&ensp; &ensp;&ensp;where t1 is a 32 bit elf which can be seen using readelf -h t1, pk is also choosen 32 bit part.   
&ensp; &ensp;&ensp; I'm compiling a 32 bit vector instruction vsetvl,  do you know which --isa=rv32iv is useful?  

![rv32i](https://user-images.githubusercontent.com/51076736/85012639-e47f1a80-b195-11ea-96c4-7f2a4c725b87.png)  
  
Thank you 
Best Regards
William

**Comment by chihminchao** [comment]
1. "bad --isa option rv32v",   i extension is at least required 
2. rv32iv should work if you only touch integer vector instruction.
3. for bbl loder illegal instruction,  insn (0000862e) is "c.mv a2, a1).  It means c extension is required or the problem should be compiled without c extension.

**Comment by WilliamWangPeng** [comment]
> 1. "bad --isa option rv32v",   i extension is at least required
> 2. rv32iv should work if you only touch integer vector instruction.
> 3. for bbl loder illegal instruction,  insn (0000862e) is "c.mv a2, a1).  It means c extension is required or the problem should be compiled without c extension.

Hi dear Chao
thanks for reply.   
```    
spike  --isa=rv32i  pk hello  
```      
 works, but when I choose   
```    
spike  --isa=rv32i  pk t2  
```    
where t2 is a 32 bit RISCV elf and contains the vsetvl intruction at t2.s firstly.  
error: bad --isa option rv32iv  

![rv32iv](https://user-images.githubusercontent.com/51076736/85032686-b0662280-b1b2-11ea-9e01-4457bbacb940.png)

**Comment by chihminchao** [comment]
vector unit must be enabled by mstatus.vs before using any of its instructions.
Do you check that ?

**Comment by WilliamWangPeng** [comment]
> vector unit must be enabled by mstatus.vs before using any of its instructions.
> Do you check that ?

oh thank you Chao, I didn't do that  
"vector unit must be enabled by mstatus.vs before using any of its instructions."  
how can I enable mstatus.vs before using any of its instructions

**Comment by WilliamWangPeng** [comment]
> vector unit must be enabled by mstatus.vs before using any of its instructions.
> Do you check that ?

hi dear chao, how can I enable mstatus.vs before using any of its instructions
