### ISSUE TITLE
Masked vslidedown 

### ISSUE THREAD

**Issue by Marc43** [riscv-software-src/riscv-isa-sim#516]
Hi,

in the 0.9 vector specification `vslidedown` behaviour is:

![image](https://user-images.githubusercontent.com/17859612/88511598-66f4c880-cfe5-11ea-9bbc-753953cb418b.png)

There's a "masked" behaviour, my question is, is this implemented in the newest version of spike?

Looking at the code it seems like not, variable `is_valid` only takes into account the current `position`,  `offset` and `vlmax`.

Thanks!
Marc

**Comment by aswaterman** [comment]
The `VI_LOOP_BASE` macro skips masked loop iterations.

**Comment by Marc43** [comment]
Okay, missed that one, sorry and thanks :)

**Comment by aswaterman** [comment]
cool, glad to help.

**Comment by Marc43** [comment]
Sorry @aswaterman for reopening this, but, is enough with skipping the iterations? Or should the value be written to 0 explicitly?

I tell you this because I am using Spike as a reference model and the values differ because the upper elements (with the mask enabled for those) are not set to 0 in Spike.

**Comment by aswaterman** [comment]
Can you provide a concrete example that violates the spec?  I'll let @chihminchao handle it from here.

**Comment by Marc43** [comment]
Sorry again for bothering you. 

I think I misunderstood how it is programmed. I understand that if the mask is not enabled (== 0), the iteration is skipped as the element must be unchanged. When mask is enabled (!= 0), the rest of the behaviour is checked and the element is written.

So, it was my fault :disappointed:
