### ISSUE TITLE
Execution of LR/SC sequences

### ISSUE THREAD

**Issue by abdullahyildiz** [riscv-software-src/riscv-isa-sim#528]
Section 8.3 of _The RISC-V Instruction Set Manual Volume I: Unprivileged ISA (Document Version 20191214-draft)_ includes the following statement on execution of store-conditional instructions:

_The SC must be to the same effective address and of the same data size as the latest LR executed by the same hart._

However, Spike simulation shows that execution of SC for doubleword succeeds even the reservation is made for a single word by LR:

```
core   0: 0x0000000000000364 (0x140e2f2f) lr.w    t5, (t3)
0 0x0000000000000364 (0x140e2f2f) x30 0xffffffff989d0b76 mem 0x00000000000c7000
core   0: 0x0000000000000368 (0x1c4e3faf) sc.d    t6, tp, (t3)
0 0x0000000000000368 (0x1c4e3faf) x31 0x0000000000000000 mem 0x00000000000c7000 0x0000000000000000
```

Shouldn't the store-conditional pair fail in such a case?

According to a comment at [riscv-isa-manual](https://github.com/riscv/riscv-isa-manual/issues/466#issuecomment-673852220) on this issue, the SC is not required to succeed.

**Comment by aswaterman** [comment]
It’s not required to succeed, but it’s not required to fail, either. So Spike’s behavior is valid, but it’s not the only valid implementation choice.
