### ISSUE TITLE
Enabling and disabling some bitmanip instructions

### ISSUE THREAD

**Issue by NazerkeT** [riscv-software-src/riscv-isa-sim#532]
Hi there,
I am a newbie in computer architecture and for the present I have finished implementing Zbb, Zbp, Zbs, Zbe groups of Bit Extension on CVA6(Ariane), and heading towards simulating and running them with benchmarks. So, as long as I did not implement the full bitmanip, I am wondering whether should I configure spike/ bitmanip for switching on and off support for some instructions. Could you advise me on this, please?

Thanks,
Best wishes,

**Comment by chihminchao** [comment]
You may reference this branch
https://github.com/riscv/riscv-isa-sim/commits/riscv-bitmanip

**Comment by NazerkeT** [comment]
Great, got it, thanks!
