### ISSUE TITLE
How spike init memory

### ISSUE THREAD

**Issue by Phantom1003** [riscv-software-src/riscv-isa-sim#547]
I read the codes in fesvr, I found that elf will load in a memif class, when sim class runs.
But I can not find the place, where the code is loaded to memory, I means since the mem is created by following codes in spike.cc
```
mems = make_mems(XXX);
```
How `mems` get the text in elf ? I read the functions like fetch_slow_path, load_slow_path... both of them directly use the value in mems, when run a bare metal program, should we suppose that the program is at the start of the ram ?

**Comment by omerguzelelectronicguy** [comment]
Hello, @Phantom1003 If you find the answer, could you write it because I need help with a similar issue. I want to locate my programs as starting from 0x40000000 instead of 0x80000000. However, when I prepare a link file that locates the program 0x40000000, it does not allow me to access that region of ram. The error message is 
```
Access exception occurred while loading payload hword.riscv:
Memory address 0x40000290 is invalid
```
Edit:
I tried also 0x70000000 and wrote it as an error message here. I fixed it now to prevent confusion
Thanks

**Comment by Phantom1003** [comment]
spike uses the mem_if interface to load instructions from the elf. For your question, I believe you also need to create a memory at 0x40000000 by using the `-m` option.

**Comment by omerguzelelectronicguy** [comment]
Thank you @Phantom1003  .
In the help message, it says `-m<n>                 Provide <n> MiB of target memory [default 2048]`.
I gave the command as `spike -d -m1024 hword.riscv` to locate 0x40000000. However, it again gave me the same error. When I gave as 0x70000000 or anything else less than 0x80000000 it gave me the same error in 0x290 according to the base. So I think I was able to locate the program in that region but it does not allow me to do something. The instruction at 0x290 (relative address)which is stated in the error message is this `    80000290:	30200073          	mret`. I am a beginner in spike so excuse me if I missed or misunderstand some clear points.

**Comment by scottj97** [comment]
The full help message for `-m` shows:
```
  -m<n>                 Provide <n> MiB of target memory [default 2048]                                                                                      
  -m<a:m,b:n,...>       Provide memory regions of size m and n bytes                                                                                         
                          at base addresses a and b (with 4 KiB alignment)                                                                                   
```

If you want memory at 0x40000000 you need `-m0x40000000:1024`

**Comment by omerguzelelectronicguy** [comment]
Exactly, Thank you so much. I wrote it in that format and it is accepted.
