### ISSUE TITLE
Make target `install-pc` fails

### ISSUE THREAD

**Issue by huksys** [riscv-software-src/riscv-isa-sim#549]
Hello, the latest commit on master, 59d450e, unfortunately introduced a bug into the build system.

The make target `install-pc`, which is a prerequisite of the `install` target, fails due to a missing rule for `riscv-disasm.pc`:
> make: *** No rule to make target 'riscv-disasm.pc', needed by 'install-pc'.  Stop.

It seems like the `install_pcs` variable is appended to by the `subproject_define` macro ([Makefile.in#L342](https://github.com/riscv/riscv-isa-sim/blob/59d450e58646bdc0af5e9250df7d6267c3c791fc/Makefile.in#L342)) which is used for each enabled subproject ([Makefile#L348](https://github.com/riscv/riscv-isa-sim/blob/59d450e58646bdc0af5e9250df7d6267c3c791fc/Makefile.in#L348)). Unfortunately, I cannot provide a patch due to my inexperience with autotools.

**Comment by aswaterman** [comment]
Thanks for the bug report.  Not clear why I didn't see that during local testing.  Will be fixed presently.
