### ISSUE TITLE
when v=1, it should report virtual instruction exception instead of illegal instruction exception when executing hfence

### ISSUE THREAD

**Issue by tianhu-zeng** [riscv-software-src/riscv-isa-sim#551]
According to Spec definition.
"When V=1, a virtual instruction trap (not an illegal instruction trap) is taken for: 
     - attempts to execute a hypervisor instruction (HLV, HLVX, HSV, or HFENCE) or to access an implemented hypervisor CSR or VS CSR;"

But spike reports an illegal instruction exception.

@avpatel, please have a check, thanks.

**Comment by avpatel** [comment]
Yes, I am aware of this.

The Hypervisor instruction emulation uses require_novirt() macro which ensures that we generate virtual instruction trap when Hypervisor instruction is executed with V=1

Regards,
Anup

**Comment by aswaterman** [comment]
I think the issue is that `require_novirt` comes after `require_privilege`, giving higher priority to the illegal instruction trap.  I will fix this one.

**Comment by tianhu-zeng** [comment]
@avpatel @aswaterman hfence has the same issue

**Comment by aswaterman** [comment]
Fixed.
