### ISSUE TITLE
when mcounteren = 1 and hcounteren = 0, access user Counter/Timers csrs should report virtual instruction exception in VS/VU.

### ISSUE THREAD

**Issue by tianhu-zeng** [riscv-software-src/riscv-isa-sim#554]
@avpatel when mcounteren = 1 and hcounteren = 0, access user Counter/Timers csrs should report virtual instruction exception in VS/VU mode. It seems that the logic is not complete in Spike.

**Comment by aswaterman** [comment]
@avpatel

**Comment by avpatel** [comment]
Spike only emulates INSTRET and CYCLE counters. The TIME counter and other counters are not emulated so for all such counters we will illegal instruction trap even in VS/VS mode.

For INSTRET and CYCLE counters, whenever HCOUNTER does not permit access to VS/VU mode will get virtual instruction trap. The get_csr() function in processor.cc is taking care of this case and jumping to throw_virtual label.

Regards,
Anup

**Comment by tianhu-zeng** [comment]
@avpatel Thanks for your reply. So if we implement TIME counter and other counters, we need to modify Spike according to Spec by myself  to emulate those counters?

**Comment by avpatel** [comment]
Yes, we sill have to modify Spike according spec whenever TIME and other counters are added.

Currently, TIME CSR is trap-n-emulated for S-mode by M-mode firmware.

**Comment by aswaterman** [comment]
So are INSTRET and CYCLE handled correctly?  Can we close this issue?

**Comment by tianhu-zeng** [comment]
Sorry for the late reply, last week we were on holiday. We will modify Spike according to Spec for all not emulated user timer/counter csrs on Spike. And we can close this issue.

**Comment by aswaterman** [comment]
Spike should continue not implementing the time CSR and related CSRs, at least by default, since that matches many current implementations.

**Comment by tianhu-zeng** [comment]
@aswaterman Got it. Thanks for your reply.
