### ISSUE TITLE
Spike use 2 to represent PRV_HS. According to Spec, privilege=2 should be reserved.

### ISSUE THREAD

**Issue by tianhu-zeng** [riscv-software-src/riscv-isa-sim#557]
@avpatel 
![image](https://user-images.githubusercontent.com/59038826/94506451-03368800-0240-11eb-83ab-cbf589e9a172.png)
According to Spec defination, privilege=2 is reserved. But spike use PRV_HS(=2) to represent HS privilege.
In this case, if I write 2 to MSTATUS.MPP when hypervisor enable, it can be written to MSTATUS.MPP. It seems mismatch with Spec.

Regards,
Tianhu

**Comment by aswaterman** [comment]
This is true: it should not be possible to set MPP=2.

**Comment by tianhu-zeng** [comment]
@aswaterman thanks for your reply. Waiting for fixing.

**Comment by avpatel** [comment]
@aswaterman the PRV_HS is a dummy mode and I am quite confident we are not setting PRV_HS to MSTATUS.MPP anywhere.

**Comment by aswaterman** [comment]
@avpatel I understand it is used as a dummy mode.  The concern is that the RISC-V software could write the mstatus.MPP field to 2.  Doing so should result in MPP containing a value other than 2, but as written, it looks like MPP will become 2.

**Comment by aswaterman** [comment]
I guess what I'm saying is I think we should revert the change to the `legalize_privilege` so that it doesn't recognize PRV_HS as a valid mode.  I don't think that will break any dummy uses of PRV_HS.

**Comment by aswaterman** [comment]
Fixed by 8966775ab443879d064a6e8419eeea82b901ccca
