### ISSUE TITLE
Write user cycle csr(0xc00) should report illegal instruction exception in VU mode when mcounteren[0]=1, hcounteren[0]=1 and scounteren[0]=0.

### ISSUE THREAD

**Issue by tianhu-zeng** [riscv-software-src/riscv-isa-sim#566]
According to Spec, it should report illegal instruction exception, but Spike report virtual instruction exception.
I read the Spike code, it seems that the out function should qualify PRV_U.
![Snipaste_2020-10-09_14-33-46](https://user-images.githubusercontent.com/59038826/95551058-993a9180-0a3c-11eb-8049-ed28c6e81cd7.png)
@avpatel

**Comment by aswaterman** [comment]
I think this one's my fault... fixing now.
