### ISSUE TITLE
MIP.SEIP should be writable if supervisor mode is implemented.

### ISSUE THREAD

**Issue by tianhu-zeng** [riscv-software-src/riscv-isa-sim#571]
![mip_spec](https://user-images.githubusercontent.com/59038826/96107738-56caf600-0f0f-11eb-9a73-eb32c5f03af5.png)
![mip_spike](https://user-images.githubusercontent.com/59038826/96107763-60ecf480-0f0f-11eb-83c0-622f01db4ff4.png)

As pictures show. MIP.SEIP should be writable if supervisor mode is implemented, but spike didn't.

**Comment by scottj97** [comment]
SEIP is part of [`supervisor_ints`](https://github.com/riscv/riscv-isa-sim/blob/956ef9ac3a66d2d6cda5df33a0e3f1c7d57ed0e0/riscv/processor.cc#L787).

Edit: and it gets masked out by the `&` operation, so never mind, you're right!

**Comment by scottj97** [comment]
Related: #139. Since Spike has no PLIC, mie.MEIE is not writable. 

But this case is a little different. Machine-mode software can simulate supervisor external interrupts, and it feels to me like that should work even without a PLIC in Spike.

**Comment by scottj97** [comment]
This was fixed in #763
