### ISSUE TITLE
Register changes after each instruction

### ISSUE THREAD

**Issue by panda1628** [riscv-software-src/riscv-isa-sim#579]
There is only PC and instruction show up in the log.

core   0: 0x0000000000001000 (0x00000297) auipc   t0, 0x0
core   0: 0x0000000000001004 (0x02028593) addi    a1, t0, 32
core   0: 0x0000000000001008 (0xf1402573) csrr    a0, mhartid

I build spike with "--enable-commitlog" option 
Is there any way to show the changed register value after each instruction?

**Comment by aswaterman** [comment]
I think you also need to use the --log-commits command-line option at
runtime

**Comment by panda1628** [comment]
Yes, you are right 
Thanks
