### ISSUE TITLE
Segmentation fault on wrong argument format

### ISSUE THREAD

**Issue by Chert-Nik** [riscv-software-src/riscv-isa-sim#583]
Spike commit SHA: 47e17aa074d617a93f9cfc9d52dca8ecbd7978b3

Built according to "Build Steps" from README.md.

Launch command (one dash before pc):
`spike -d -pc=0x1000 pk`
Leads to segmentation fault.

If launch command is (two dashes before pc):
`spike -d --pc=0x1000 pk`
it works as expected.

**Comment by aswaterman** [comment]
Thanks for pointing this out.
