### ISSUE TITLE
A confusion about sync vsstatus to mstatus.

### ISSUE THREAD

**Issue by tianhu-zeng** [riscv-software-src/riscv-isa-sim#584]
1. In Spike, when executing mret/sret, it will sync vsstatus.{sd,fs,vs} to mstatus.{sd,fs,vs}. 
2. The Spike checks mstatus.fs when access fp csr.

Confusions:
1. Why bonds sync operations to mret/sret? 
2. In Spec, accessing fp csr need checking sstatus.fs and vsstatus.fs in VS-mode. But in Spike, due to the sync operation, it just check mstatus.fs. It seems that the Spike mismatch with the Spec. 
![spec](https://user-images.githubusercontent.com/59038826/97246414-3fa5d580-1838-11eb-81a1-8a0edc5c5595.png)
![spike-set_virt](https://user-images.githubusercontent.com/59038826/97246429-47657a00-1838-11eb-9954-d51a46f8af9d.png)
![access-fp-csr](https://user-images.githubusercontent.com/59038826/97246450-4e8c8800-1838-11eb-915a-be06f6f20446.png)

**Comment by tianhu-zeng** [comment]
@avpatel @aswaterman

**Comment by aswaterman** [comment]
You don't need to @-mention me, since I don't maintain this code.

**Comment by tianhu-zeng** [comment]
@avpatel could you have a look about this issue? thanks.

**Comment by avpatel** [comment]
The generating the illegal-instruction trap considering both SSTATUS.FS and VSSTATUS.FS was missed out whereas updating dirty state is taken care by set_virt() which is called to change processor virt state.

Linux, KVM and Xvisor, don't see any issues because all these software set SSTATUS.FS and VSSTATUS.FS to initial state (not disabled).

**Comment by tianhu-zeng** [comment]
understand, thanks for your reply.

**Comment by francis4096** [comment]
> The generating the illegal-instruction trap considering both SSTATUS.FS and VSSTATUS.FS was missed out whereas updating dirty state is taken care by set_virt() which is called to change processor virt state.
> 
> Linux, KVM and Xvisor, don't see any issues because all these software set SSTATUS.FS and VSSTATUS.FS to initial state (not disabled).

@avpatel, Do you mean that checking VSSTATUS.FS needs to be added to "require_fp" macro? 
I tried to modify the require_fp marco to like this.
#define require_fp require((((STATE.mstatus & MSTATUS_FS) != 0) & (STATE.v == 0)) | (((STATE.mstatus & MSTATUS_FS) != 0) & ((STATE.vsstatus & SSTATUS_FS) != 0) & STATE.v))

But kvm complaints illegal instruction after Run /virt/init as init process. The sepc address is "fld ft0,0(a0)".

[    2.601769] Freeing unused kernel memory: 2136K
[    5.024622] Run /virt/init as init process
[    8.980426] kvm [49]: VCPU exit error -14
[    8.980700] kvm [49]: SEPC=0xffffffe000005282 SSTATUS=0x8000000200006120 HSTATUS=0x2002001c0
[    8.981270] kvm [49]: SCAUSE=0x2 STVAL=0x53007 HTVAL=0x0 HTINST=0x0
KVM_RUN failed: Bad address

Do you have any idea about this issue?

**Comment by francis4096** [comment]
@avpatel ，Could you help to check this issue?

**Comment by avpatel** [comment]
Apologies for the delay.

Your require_fp() macro looks incorrect because it uses "&" for logical-AND and "|" for logical-OR

Can try the below definition of require_fp() macro ?

```
#define require_fp require((((STATE.mstatus & MSTATUS_FS) != 0) && (STATE.v == 0)) || (((STATE.mstatus & MSTATUS_FS) != 0) && ((STATE.vsstatus & SSTATUS_FS) != 0) && STATE.v))
```

**Comment by aswaterman** [comment]
@avpatel / @francis4096  Let me know when the PR is fixed and I should merge it.

**Comment by francis4096** [comment]
> Apologies for the delay.
> 
> Your require_fp() macro looks incorrect because it uses "&" for logical-AND and "|" for logical-OR
> 
> Can try the below definition of require_fp() macro ?
> 
> ```
> #define require_fp require((((STATE.mstatus & MSTATUS_FS) != 0) && (STATE.v == 0)) || (((STATE.mstatus & MSTATUS_FS) != 0) && ((STATE.vsstatus & SSTATUS_FS) != 0) && STATE.v))
> ```

@avpatel  Thank you for correction. I fixed it in PR. But the KVM issue still exists. I think there may be something wrong with KVM software. Could we merge this PR to spike first?
