### ISSUE TITLE
Misaligned LR should take exception

### ISSUE THREAD

**Issue by scottj97** [riscv-software-src/riscv-isa-sim#591]
The A extension spec says:

> For LR and SC, the A extension requires that the address held in rs1 be naturally aligned to the size of the operand (i.e., eight-byte aligned for 64-bit words and four-byte aligned for 32-bit words). If the address is not naturally aligned, an address-misaligned exception or an access-fault exception will be generated.

When building Spike with `--enable-misaligned`, as of 956ef9ac3a66d2d6cda5df33a0e3f1c7d57ed0e0 I observe this exception occurring for SC ([from check_load_reservation()](https://github.com/riscv/riscv-isa-sim/blob/956ef9ac3a66d2d6cda5df33a0e3f1c7d57ed0e0/riscv/mmu.h#L259) -- added for #431) but the same exception does not occur for the LR.

It's not clear where to add this check while maintaining the proper exception prioritization. It needs to be higher priority than page fault or access fault. (The spec allows it optionally to be lower priority but that wouldn't be consistent with Spike's SC implementation.)

The check could be the first thing in acquire_load_reservation(), but that's called after the load has already occurred, which is too late.

**Comment by aswaterman** [comment]
Always nice to hear from you, @scottj97.  I think your proposed fix in #592 is the way to go.
