### ISSUE TITLE
MRET and SRET will clear mstatus.MPRV when leaving M-mode.

### ISSUE THREAD

**Issue by tianhu-zeng** [riscv-software-src/riscv-isa-sim#597]
In Spec 3.1.6.3 Memory Privilege in mstatus Register, "An MRET or SRET instruction that changes the privilege mode to a mode less privileged than M also sets MPRV=0."

It seems that the Spike didn't do the operation. Please have a check, thanks.

@aswaterman

**Comment by aswaterman** [comment]
Spike's behavior conforms to the ratified priv-1.11 standard; the sentence you quoted was added as part of priv-1.12-draft.  So it's not really a bug; it's a yet-to-be-implemented feature.  We'll get around to it eventually.

**Comment by tianhu-zeng** [comment]
OK, got it!

**Comment by scottj97** [comment]
This was implemented in 327084128246e5cf562293cfe82d2570a6d5629e
