### ISSUE TITLE
Debugging output present when running any simulation operation that involves `addr_to_mem`.

### ISSUE THREAD

**Issue by hawkinsw** [riscv-software-src/riscv-isa-sim#609]
https://github.com/riscv/riscv-isa-sim/blob/f4f6e12eeeabccc31853ab4e8570219d1f5cba37/riscv/sim.cc#L358

Thank you to @chihminchao for pointing out this issue. I am terribly sorry for introducing this in the first place! Patch coming.

Will

**Comment by aswaterman** [comment]
Resolved by #610
