### ISSUE TITLE
--isa=rv32imaf fails to run floating point instruction 

### ISSUE THREAD

**Issue by panda1628** [riscv-software-src/riscv-isa-sim#626]
I run into similar issue #147

spike -l --isa=rv32imaf --log-commits fadd.s.bfd

core   0: 0xffffffffc0500310 (0x0021f1d3) fadd.s  ft3, ft3, ft2
core   0: exception trap_illegal_instruction, epc 0xffffffffc0500310
core   0:           tval 0x000000000021f1d3
core   0: >>>>  _trap_handler

Do I miss anything? Thx

_Originally posted by @panda1628 in https://github.com/riscv/riscv-isa-sim/issues/147#issuecomment-758852443_

**Comment by chihminchao** [comment]
Do you enable the mstatus.fs by setting non-zero value ?

**Comment by panda1628** [comment]
Yes, that is.  Tx
