### ISSUE TITLE
wfi not printed in commit log

### ISSUE THREAD

**Issue by rnitya** [riscv-software-src/riscv-isa-sim#642]
The commit log (--log-commits) ignores legal wfi instructions while dumping the output. These can be seen in "spike -l" execution log though. For example, in riscv-tests rv64mi/illegal and rv64si/wfi, the wfi instructions are never printed. Is this behaviour intentional? 

Thanks.

**Comment by aswaterman** [comment]
The commit log feature is not the most carefully vetted thing.  I've fixed this bug.

**Comment by rnitya** [comment]
Thanks Andrew.
