### ISSUE TITLE
Incorrect dependency of mstatus.FS writability on misa.S?

### ISSUE THREAD

**Issue by jameshippisley** [riscv-software-src/riscv-isa-sim#643]
If I read this code correctly, it looks like the mstatus.FS field is writable on cores which implement S-mode, even if they do not implement F or V extensions, which seems to be incorrect (unless I'm misunderstanding the spec):

https://github.com/riscv/riscv-isa-sim/blob/master/riscv/processor.cc#L917-L918

bool has_fs = supports_extension('S') || supports_extension('F')
                  || supports_extension('V');

**Comment by aswaterman** [comment]
The ISA spec requires this behavior. It supports transparent emulation of the FP extension.
