### ISSUE TITLE
address translation in user mode without paging

### ISSUE THREAD

**Issue by gystar** [riscv-software-src/riscv-isa-sim#688]
I'm writing a small OS core running on spike.I set the satp CSR to 0 to disable paging  for some reason.
Before I enter U mode via "sret", I set the sp register to 0x0000000080040000 for user stack.
When I use "ecall" to do something in S mode, I pass the address of a variable on user stack to U mode.
But I find that the address is  0xffffffff80039800 in S mode !

Should the address be 0x0000000080039800 ?  
Where does the 0xffffffff come from?

Thanks for any answer！

**Comment by chihminchao** [comment]
Do you run with rv32 ?

**Comment by gystar** [comment]
No，it is rv64

**Comment by gystar** [comment]
I find it happens because I use "lw" to load 0x80040000 into a 64-bit register.
