### ISSUE TITLE
Instructions in Zvlsseg are warned to be illegal

### ISSUE THREAD

**Issue by Arima-Kawori** [riscv-software-src/riscv-isa-sim#689]
I'm using commit 67b7edd0270d5d074136eb45474477d15aeee725, which supports rvv-0.9 and Zvlsseg as it shows in README.md.
But when I try to write some assembly codes to test, many instructions in Zvlsseg are considered to be illegal, such as     `vlseg4e32.v v4, (a0)`, `vlsseg4e32.v v8, (a0), zero` and so on.
There is only one rvv instruction `vsetvli x0, t0(unsigned -1 in it), e32` before.
I'll appreciate it if anyone could tell me why is that and maybe how to solve this problem. Thanks!

**Comment by chihminchao** [comment]
@Arima-Kawori 
Do you specify the extension on --isa ?
ex : rv64gc_zvlsseg

**Comment by Arima-Kawori** [comment]
> @Arima-Kawori
> Do you specify the extension on --isa ?
> ex : rv64gc_zvlsseg

I tried `--isa=rv64gcv_zvlsseg` and it works.
Thank you very much!
