### ISSUE TITLE
How could we get the value of the misa register?

### ISSUE THREAD

**Issue by zhengxiaolinX** [riscv-software-src/riscv-isa-sim#710]
Hi,

I've tried 
```
int misa;
asm volatile("csrr x0, misa" : "=r" (misa));
printf("%x\n", misa);
```
and got an `An illegal instruction was executed!` message in spike. I wonder how can I get the value of this register, or how could we get CPU features of the current simulator, e.g. whether the C extension is supported. Did I get something wrong? I am not so familiar with this, and thanks in advance.

**Comment by aswaterman** [comment]
`misa` is only readable in M-mode.  If you are running a user program using `pk`, your program is running in U-mode, so it is impossible to directly read that register.

**Comment by zhengxiaolinX** [comment]
> `misa` is only readable in M-mode. If you are running a user program using `pk`, your program is running in U-mode, so it is impossible to directly read that register.

Thank you @aswaterman for replying to this! 
Just one more question, I wonder how to detect whether the C extension is supported on the current core by using some instructions. Thanks!

**Comment by aswaterman** [comment]
There isn't a straightforward way to check.  You can try executing a C-extension instruction and see if you get an exception.

On RISC-V Linux, a program's ELF header indicates whether it requires the C extension, and the kernel's ELF loader will refuse to load the program if the processor does not support C.

**Comment by zhengxiaolinX** [comment]
> There isn't a straightforward way to check. You can try executing a C-extension instruction and see if you get an exception.
> 
> On RISC-V Linux, a program's ELF header indicates whether it requires the C extension, and the kernel's ELF loader will refuse to load the program if the processor does not support C.

Thank you. I really appreciate your help and the details.
