### ISSUE TITLE
How to execute c programs in spike using extensions such as M,A,F,B,V and others.

### ISSUE THREAD

**Issue by nikita890-art** [riscv-software-src/riscv-isa-sim#711]
I am currently using a 32-bit spike and i am trying to run my c code with extensions such as M,A,F,B,V etc. , but i dont really know on what command to give in the terminal so as to execute the program with these extensions.
Presently i am using these commands for compiling and to run,
riscv32-unknown-elf-gcc <file name>
RISCV/riscv-isa-sim/build/spike  --isa=RV32IMAC   RISCV/riscv-pk/build/pk  a.out

What changes do i need to make in these commands to execute it using extensions?

**Comment by LakshmiKanth-77** [comment]
You should compile it with same extension and then simulate with same extension .
riscv32-unknown-elf-gcc -march= rc32imaf .c file -o object file[some letter]

**Comment by nikita890-art** [comment]
thank you!!!!it works now
