### ISSUE TITLE
how do i convert my c code to assembly code in spike using riscv64-unknown-elf-gcc compiler?

### ISSUE THREAD

**Issue by nikita890-art** [riscv-software-src/riscv-isa-sim#712]
The reason i want to convert c code to assembly code is so that I can see how my code changes when compiled using different extensions.

i dont really know how to do the conversion.

Please help!!

**Comment by chihminchao** [comment]
try "gcc -S code.c"

**Comment by scottj97** [comment]
Closing as not a Spike issue.
