### ISSUE TITLE
What exactly does the M extension do to a c code to multiply 2 numbers

### ISSUE THREAD

**Issue by nikita890-art** [riscv-software-src/riscv-isa-sim#714]
I executed a c code to multiply 2 numbers and checked the assembly code for both cases with and without the "M" extension.
I had more lines of assembly code for executing my c code without the extension "M" compared to that when executed with "M".
What exactly is the extension doing to lessen the code size?

**Comment by aswaterman** [comment]
The M instruction adds (among other things) the MUL instruction, which multiplies two integers.  Without it, a multi-instruction sequence is needed to multiply two integers.

**Comment by nikita890-art** [comment]
Got it..thanks
