### ISSUE TITLE
What is the use of compression extension "C" in the RISC-V ISA?

### ISSUE THREAD

**Issue by nikita890-art** [riscv-software-src/riscv-isa-sim#715]
I have executed a c program with and without the C extension and I get different amount of lines for the assembly code for both executions. What is the C extension doing to the c code exactly?

**Comment by mwachs5** [comment]
It is taking the assembly code that comes out of the compiler and turning some common 32-bit instructions into their 16-bit shorthand equivalents ("Compressing" them).

**Comment by nikita890-art** [comment]
Thank you so much..
I get more number of instructions and clocks when I use the C extension compared to when I dont use it.
Isnt C extension suppose to reduce the number of instructions and clock?

**Comment by mwachs5** [comment]
no. C extension is only intended to reduce the size of the binary, it doesn't say anything about how long it takes to execute the instructions, could be more or less depending on the implementation. I don't know how it is emulated in `riscv-isa-sim`.

**Comment by nikita890-art** [comment]
oh..ok...thank you!!
