### ISSUE TITLE
Why do i get more number of cycles and instructions when i use the "C" extension is RISCV?

### ISSUE THREAD

**Issue by nikita890-art** [riscv-software-src/riscv-isa-sim#717]
I ran my c code in -s mode with and without C extension.
Why am i getting more number of cycles, instructions and ticks when i use C extension compared to when i am not?
Isnt C extension suppose to reduce my code size??

**Comment by zhongchengyong** [comment]
As far as I know, spike is just a instruction set simulator(ISS), it doesn't support count cycles.
1. what's your -s mode? spike doesn't have this option.
2. C extension does reduce code size, but spike count the retired instruction only, not cycles. How do you count execution cycles?
