### ISSUE TITLE
How can i get the default versions of the ISA extensions?

### ISSUE THREAD

**Issue by nikita890-art** [riscv-software-src/riscv-isa-sim#719]
I want to execute my code using the extensions B and V but when I try to compile using rv64-unknown-elf-gcc compiler, I get an error saying that:

Error: cannot find default versions of the ISA extension 'b'

How can I get the default versions?

**Comment by zhongchengyong** [comment]
Run 'spike --help', it says:
>  --isa=<name>          RISC-V ISA string [default RV64IMAFDC]  

Maybe you can run your program by set the --isa option with 'RV64IMAFDCBV'

**Comment by scottj97** [comment]
OP apparently has a compiler question. Closing as not a Spike issue.
