### ISSUE TITLE
how to solve problem of "unsupported ISA subset k"

### ISSUE THREAD

**Issue by nikita890-art** [riscv-software-src/riscv-isa-sim#732]
I am trying to run my c code using riscv64 gcc compiler with the extension K for cryptography.
But i am getting the following error:
how to solve problem of "unsupported ISA subset k"

I dont know whats wrong.

Please help!

**Comment by aswaterman** [comment]
Seems to work for me.  Maybe you are using an older version of Spike than you think you are?

```
$ spike --isa=rv64gck pk
bbl loader
tell me what ELF to load!
```

**Comment by nikita890-art** [comment]
@aswaterman , You are right....I had the older version of spike.
I just want to know if I can update my spike version and if so, then what commands i need to use.

**Comment by scottj97** [comment]
Closing as apparently resolved.
