### ISSUE TITLE
Can i run a RV32I supported code in RV64I

### ISSUE THREAD

**Issue by nikita890-art** [riscv-software-src/riscv-isa-sim#735]
Hi.
I am trying to run a c code using RV32I on  spike..but I have RV64I...
Is it possible to run both RV32 and RV64 on spike...
If so, then what command can I use?

Thank you...

**Comment by TommyMurphyTM1234** [comment]
Any use?
https://github.com/riscv/riscv-isa-sim/issues/453#issuecomment-623839508

**Comment by scottj97** [comment]
Closing as stale, and not a Spike issue.
