### ISSUE TITLE
How can I save the assembly code in ubuntu?

### ISSUE THREAD

**Issue by nikita890-art** [riscv-software-src/riscv-isa-sim#736]
Hi.
I compiled my C code and have generated the assembly code for the same using these commands:

riscv64-unknown-elf-gcc -march=rv64imafdc -g file.c -o abcd

riscv64-unknown-elf-objdump -d file.o

I have got the assembly code but i want to save it in a .asm file...I am not sure how to save it in an .asm file.

Please help!

**Comment by chihminchao** [comment]
redirect ? 
`riscv64-unknown-elf-objdump -d file.o > file.asm`

**Comment by nikita890-art** [comment]
> redirect ?
> `riscv64-unknown-elf-objdump -d file.o > file.asm`

Thank you....

**Comment by scottj97** [comment]
@nikita890-art please close all these issues if you are satisfied with their resolution.
