### ISSUE TITLE
Error: import-im6.q16: attempt to perform an operation not allowed by security policy

### ISSUE THREAD

**Issue by nikita890-art** [riscv-software-src/riscv-isa-sim#737]
I am trying to import RV32 using the command:

sudo import RV32

But I get this error:

Error: import-im6.q16: attempt to perform an operation not allowed by security policy 'PS' @error/constitute.c/IsCoderAuthorized/408.

How can I resolve this issue?

**Comment by Vortex1x1x1x** [comment]
hey im having the same problem but with torch what did you do to fix it?
