### ISSUE TITLE
How to run a C code on spike using the rvnewop Instruction simulator tool ?

### ISSUE THREAD

**Issue by nikita890-art** [riscv-software-src/riscv-isa-sim#738]
Hi all,

I am trying to run the dump file for my c code using rvnewop tool on spike to get the Histogram for the code. 

But I have no clue on what commands I need to use to run my code using this tool on ubuntu.

What should I do?

**Comment by aswaterman** [comment]
Sorry, I don’t know about that tool, and thus I can’t support it.

**Comment by nikita890-art** [comment]
> Sorry, I don’t know about that tool, and thus I can’t support it.

Is there anyone you might know that can answer my doubt..?
