### ISSUE TITLE
How to disable unaligned load/store support for spike ?

### ISSUE THREAD

**Issue by d-thakkar** [riscv-software-src/riscv-isa-sim#753]
Hi, I am running spike against my RTL. My RTL does not support load and store to unaligned memory address values. But the spike does, is there a way I can disable it ?

**Comment by aswaterman** [comment]
By default, Spike _does_ raise an exception on misaligned loads and stores.  Full handling of misaligned accesses is only provided when `--enable-misaligned` is passed to `configure`.

**Comment by d-thakkar** [comment]
Oh yes, I built it by passing the --enable-misaligned switch. Is there a way to disable it after it is configured or I need to build it again ?

**Comment by aswaterman** [comment]
You need to rebuild it.

**Comment by d-thakkar** [comment]
Ok thanks
