### ISSUE TITLE
spike trace too large

### ISSUE THREAD

**Issue by WeiyanZh** [riscv-software-src/riscv-isa-sim#757]
Hi，

I have a simple program. I want to count the dynamic instructions count of this main program. So I run main on spike using following command. However, the generated main_trace.log is too large and the simulation cannot stop running. 
Why does the spike run for so long? 
Can I just only generate the instructions of main part?

$ spike -l pk main 2> main_trace.log

**Comment by aswaterman** [comment]
it takes a lot of instructions to get to the start of the user-level program.  You can always use Unix utilities to snip parts of the log, e.g., to collect lines 100000-120000, `spike -l pk main 3>&1 1>&2 2>&3 | tail -n +100000 | head -n20000 > main_trace.log`

**Comment by WeiyanZh** [comment]
thank you

**Comment by scottj97** [comment]
Closing as apparently resolved.
