### ISSUE TITLE
FMIN/FMAX should return canonical NaN if either input is sNaN

### ISSUE THREAD

**Issue by aswaterman** [riscv-software-src/riscv-isa-sim#76]
At the moment fmin(sNaN, normal) returns normal, not qNaN.

**Comment by aswaterman** [comment]
Likewise, fmin(qNaN, qNaN) should canonicalize the NaN.

**Comment by quark17** [comment]
Commit ba28ea06 appears to have reintroduced the old behavior, by removing "|| softfloat_exceptionFlags" from the condition of whether to return the canonical NaN.  Has the spec changed, or has this reintroduced the bug?

**Comment by aswaterman** [comment]
The former: https://github.com/riscv/riscv-isa-manual/blob/master/src/preface.tex#L46
