### ISSUE TITLE
rvp: SWAP16 old encoding

### ISSUE THREAD

**Issue by marcfedorow** [riscv-software-src/riscv-isa-sim#765]
Since 0.9.3 p-spec SWAP16 is an alias to PKBT16.
Replacing SWAP16's encoding with PKBT16's one makes spike interpret all the PKBT16 insns as SWAP16 (even if rs1!=rs2).
I solved this by just removing SWAP16 at all but I am not sure this is the right way.

**Comment by aswaterman** [comment]
This sounds right to me on the surface.  PR it?

**Comment by aswaterman** [comment]
Resolved by #766
