### ISSUE TITLE
Misaligned load using LH is causing "address misaligned" excp instead of "access fault" excp

### ISSUE THREAD

**Issue by nadiga-ventana** [riscv-software-src/riscv-isa-sim#774]
I'm using RISCOF for architectural compliance of our RTL vs Spike/Sail.
For misaligned load ops like LH/LW etc Spike traps with MCAUSE of 4 (load address misaligned)

**Comment by aswaterman** [comment]
The ISA spec offers flexibility on the priority of these exceptions.  Both implementations are probably correct.
