### ISSUE TITLE
why does acquire_load_reservation()  not look up VA to PA mapping in  tlb before calling translate()?

### ISSUE THREAD

**Issue by tonglvyi** [riscv-software-src/riscv-isa-sim#775]
the translation from VA to PA in acquire_load_reservation(), defined in [riscv/mmu.h](https://github.com/riscv/riscv-isa-sim/blob/master/riscv/mmu.h), uses translate() directly, not considering the situation where this translation has been done and stored in tlb_data. it seems like not being efficient, right?

**Comment by aswaterman** [comment]
LR instructions are dynamically infrequent in practice, and I am not concerned with Spike being slightly slowed down in such cases.
