### ISSUE TITLE
Warning with recent versions of dtc (<stdin>:20.39-24.9: Warning (interrupt_provider): /cpus/cpu@0/interrupt-controller: Missing #address-cells in interrupt provider)

### ISSUE THREAD

**Issue by moy** [riscv-software-src/riscv-isa-sim#784]
Recent versions of `dtc` introduced a [new warning for missing #address-cells](https://github.com/qemu/dtc/commit/81e0919a3e211844245a3c19be28610f930c13c0), and the warnings pops when running `spike`:

```
bash-5.1$ spike pk
<stdin>:20.39-24.9: Warning (interrupt_provider): /cpus/cpu@0/interrupt-controller: Missing #address-cells in interrupt provider
bbl loader
tell me what ELF to load!
```

The missing field should be added in [make_dts()](riscv/dts.cc) I guess.

**Comment by sbeamer** [comment]
I'm also getting this error. I just built new homebrew bottles for macOS, but I think this issue is more generic than that.

**Comment by aswaterman** [comment]
@terpstra

**Comment by sbeamer** [comment]
Thanks!

**Comment by eminedrmsky** [comment]
I am getting same error when I run:
spike --isa=RV32IM $RISCV/riscv32-unknown-elf/bin/pk hello.out
Here is the error:
<stdin>:20.39-24.9: Warning (interrupt_provider): /cpus/cpu@0/interrupt-controller: Missing #address-cells in interrupt provider
bbl loader
