### ISSUE TITLE
Which instruction set combination can support a simple Linux operating system

### ISSUE THREAD

**Issue by LangQingjie** [riscv-software-src/riscv-isa-sim#787]
Hello, I am preparing to develop a processor core that can support Linux operating system in order to complete my course homework. But now I'm very confused because I don't know which instruction set is the least needed to support a Linux operating system.

**Comment by aswaterman** [comment]
At bare minimum, the Linux kernel requires the RV32IMA instruction set, but in practice, distros require RV64IMAFDC.  In both cases, a lot of privileged architecture support is also needed.

**Comment by LangQingjie** [comment]
sorry,  I have closed the issue on riscv/riscv-tools.

**Comment by LangQingjie** [comment]
Hello, does privileged architecture support refer to privilege level and debug mode?

**Comment by aswaterman** [comment]
Debug is not necessary to run Linux.

**Comment by scottj97** [comment]
Closing as apparently resolved.
