### ISSUE TITLE
Spike shoots error for 32-bit appliaction "terminate called after throwing an instance of 'trap_load_access_fault'"

### ISSUE THREAD

**Issue by ramazankaan95** [riscv-software-src/riscv-isa-sim#791]
Hi everyone,

I am trying to compile and simulate a simple program in RV32IMC isa. I need this as I will use the output of this simulation for my project includes verification of a riscv core with RV32IMC. For now, I only need to see the simulation log of a simple program. So, I am not worried about memory layout or anything else for now. To do this,

I have built riscv toolchain with:
`./configure --prefix=/opt/riscv --enable-multilib`
Spike with:
`../configure --prefix=/opt/riscv --with-isa=rv32imc`
Proxy Kernel:
`../configure --prefix=/opt/riscv --host=riscv64-unknown-elf`

I don't know if I really need PK (I installed it anyways), because the tests on that core will not call any system function as it will run on hardware only. If you have advices on PK, I would be happy to hear, I am not much familiar with it.

Here is my C code:
`int main()
{
        int a = 0;
        int b = 3;
        int c = a + b;
}`

This is how I compile and create binary:
`riscv64-unknown-elf-gcc main.c -o main -march=rv32imc -mabi=ilp32`

When I try to simulate with PK:
`spike -l pk main`
After some execution, I start to receive this and the simulation never ends:
`core   0: exception trap_illegal_instruction, epc 0x800001c0
core   0:           tval 0x04a13823
core   0: 0x80000004 (0x34011173) csrrw   sp, mscratch, sp
core   0: 0x80000008 (0x1a010863) beqz    sp, pc + 432
core   0: 0x8000000c (0x04a13823) sd      a0, 80(sp)
core   0: exception trap_illegal_instruction, epc 0x8000000c
core   0:           tval 0x04a13823
core   0: 0x80000004 (0x34011173) csrrw   sp, mscratch, sp
core   0: 0x80000008 (0x1a010863) beqz    sp, pc + 432
core   0: 0x8000000c (0x04a13823) sd      a0, 80(sp)
core   0: exception trap_illegal_instruction, epc 0x8000000c
core   0:           tval 0x04a13823
core   0: 0x80000004 (0x34011173) csrrw   sp, mscratch, sp
core   0: 0x80000008 (0x1a010863) beqz    sp, pc + 432
core   0: 0x8000000c (0x04a13823) sd      a0, 80(sp)
core   0: exception trap_illegal_instruction, epc 0x8000000c
core   0:           tval 0x04a13823
core   0: 0x80000004 (0x34011173) csrrw   sp, mscratch, sp
core   0: 0x80000008 (0x1a010863) beqz    sp, pc + 432
core   0: 0x8000000c (0x04a13823) sd      a0, 80(sp)
core   0: exception trap_illegal_instruction, epc 0x8000000c
core   0:           tval 0x04a13823
core   0: 0x80000004 (0x34011173) csrrw   sp, mscratch, sp
core   0: 0x80000008 (0x1a010863) beqz    sp, pc + 432
core   0: 0x8000000c (0x04a13823) sd      a0, 80(sp)
core   0: exception trap_illegal_instruction, epc 0x8000000c
core   0:           tval 0x04a13823
`
When I try to simulate without PK, simulation does not start and I get:
`terminate called after throwing an instance of 'trap_load_access_fault'`

I am running all those applications on Windows Subsystem for Linux (WSL) - Ubuntu 20.04.3 LTS

I hope someone would explain what I am doing wrong here. Also any guidance is appreciated.

Best, Kaan.

**Comment by scottj97** [comment]
The root problem is that you're trying to execute "sd a0, 80(sp)" (store-double) on a 32-bit machine, where 64-bit stores are illegal instructions.

Maybe the proxy kernel was compiled for rv64?

**Comment by scottj97** [comment]
Closing as not a Spike problem.
