### ISSUE TITLE
How can I add some csr in spike and open interface for pk

### ISSUE THREAD

**Issue by weinan003** [riscv-software-src/riscv-isa-sim#89]
I custom two csr  (mbase,mbound) in spike projectfor Mbb policy which present on riscv-privileged-v1.9.1 specification.
My step  is as follow:
1.add "mbase" and "mbound" in "parse-opcodes" file "riscv-opcode" project and run "make install"
2.in mstatus_init function ,"minit.c" file pk project, add "write_csr(mbound, ms);" to test if it works

when I compile pk project ,gcc failed and notify as follow:
     ../machine/minit.c: Assembler messages:
     ../machine/minit.c:25: Error: Instruction csrw requires absolute expression

**Comment by sorear** [comment]
binutils has its own copy of the CSR map.  you can either modify binutils or use a numeric CSR access in minit.c.

You will want to familiarize yourself with the gcc inline asm syntax if you have not already.

This is not a spike issue.
